library(shiny)
if (!require("shiny")) install.packages("shiny")
library(bs4Dash)
if (!require("bs4Dash")) install.packages("bs4Dash")
library(shinyWidgets)
if (!require("shinyWidgets")) install.packages("shinyWidgets")
library(shinyjs)
if (!require("shinyjs")) install.packages("shinyjs")
library(googlesheets4)
library(scales)
library(sortable)
library(stringi)
gs4_auth(cache = ".secrets", email = TRUE, use_oob = TRUE)
